<ul class="news_ul">
                                <li class="nlz">
                                    <em class="nshz">
                                        [field:pubdate function="MyDate('d',@me)"/]
                                    </em>
                                    <em class="nmon">
                                        [field:pubdate function="MyDate('m',@me)"/]月
                                    </em>
                                </li>
                                <li class="nlr">
                                    <h3>
                                        <a href="[field:arcurl /]" target="_blank" title="[field:title /]">
                                            [field:title /]
                                        </a>
                                    </h3>
                                    <p>
                                        [field:description /]
                                    </p>
                                </li>
                        </ul>