<?php
$z[0]=Array("pubdate","",167,210);
$z[0][4]=array();
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",350,393);
$z[1][4]=array();
$z[1][4]['function']="MyDate('m',@me)";
$z[2]=Array("arcurl","",621,637);
$z[2][4]=array();
$z[3]=Array("title","",662,677);
$z[3][4]=array();
$z[4]=Array("title","",725,740);
$z[4][4]=array();
$z[5]=Array("description","",912,933);
$z[5][4]=array();

?>