<li class="newimg">
                                        <a title="[field:title /]" href="../FrontNews/news_detail/id/251.htm" tppabs="https://beyondin.com/../FrontNews/news_detail/id/251" target="_blank">
                                            <img src="" onerror="no_pic(this);" alt="[field:title /]" />
                                        </a>
                                    </li>
                                    <li class="newwz">
                                        <a href="../FrontNews/news_detail/id/251.htm" tppabs="https://beyondin.com/../FrontNews/news_detail/id/251" target="_blank" title="[field:title /]">
                                            [field:title /]
                                        </a>
                                    </li>
                                    <li class="newjj">
                                    [field:shorttitle /]
                                    </li>
                                    <li class="newrq">
                                        [field:pubdate function="MyDate('Y-m-d',@me)"/]
                                    </li>