<?php
$z[0]=Array("title","",71,86);
$z[0][4]=array();
$z[1]=Array("litpic","",265,281);
$z[1][4]=array();
$z[2]=Array("title","",312,327);
$z[2][4]=array();
$z[3]=Array("title","",649,664);
$z[3][4]=array();
$z[4]=Array("title","",712,727);
$z[4][4]=array();
$z[5]=Array("description","",910,931);
$z[5][4]=array();
$z[6]=Array("pubdate","",1072,1119);
$z[6][4]=array();
$z[6][4]['function']="MyDate('Y-m-d',@me)";

?>