<li class="img_nav" style="width: 100%;">
                <a href="[field:arcurl /]"  class="nav_a clearfix" style="background: #eee;">
                    <img src="[field:litpic /]"  onerror="no_pic(this);" style="float: left;width: 50%;height: 120px;"/>
                    <div class="deputy_bg">
                        <h4>名称：[field:title /]</h4>
                        <span></span>
                        <p>[field:gongneng /]</p>
                    </div>
                </a>
            </li>