<?php
$z[0]=Array("array"," \r\n            if(@me['platform']=='微信公众号')  \r\n            {\r\n                @me='123';\r\n            }\r\n            ",0,168);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",229,245);
$z[1][4]=array();
$z[2]=Array("litpic","",302,318);
$z[2][4]=array();
$z[3]=Array("title","",505,520);
$z[3][4]=array();
$z[4]=Array("catname","",568,585);
$z[4][4]=array();
$z[5]=Array("gongneng","",637,655);
$z[5][4]=array();

?>