<li class="img_nav">
                <a href="[field:arcurl /]"  class="nav_a clearfix">
                    <img src="[field:litpic /]"  onerror="no_pic(this);" />
                    <div class="deputy_bg">
                        <h4>名称：[field:title /]</h4>
                        <span></span>
                        <p>[field:gongneng /]</p>
                    </div>
                </a>
            </li>