<li class="newimg">
                                        <a title="[field:title /]" href="[field:arcurl /]" target="_blank">
                                            <img src="[field:litpic /]" onerror="no_pic(this);" alt="[field:title /]" />
                                        </a>
                                    </li>
                                    <li class="newwz">
                                        <a href="[field:arcurl /]" target="_blank" title="[field:title /]">
                                            [field:title /]
                                        </a>
                                    </li>
                                    <li class="newjj">
                                    [field:description /]
                                    </li>
                                    <li class="newrq">
                                        [field:pubdate function="MyDate('Y-m-d',@me)"/]
                                    </li>