<a class="nwxg cur" onmousemove="nwxshi({dede:field name="id"/})" id="nwa_1" href="javascript:;">
                           {dede:field name='typename'/}
                        </a>
                        <!-- <a class="nwxg" onmousemove="nwxshi(2)" id="nwa_2" href="javascript:;">
                            公司动态
                        </a>
                        <a class="nwxg" onmousemove="nwxshi(3)" id="nwa_3" href="javascript:;">
                            行业动态
                        </a> -->