<li class="img_nav">
                <a href="../FrontCase/case_detail/case_id/81.htm" class="nav_a clearfix">
                    <img src="[field:url /]" onerror="no_pic(this);" />
                   <div class="case_bg">
                        <div class="case-box">
                            <h4>名称：[field:title /]</h4>
                            <h4>类型：[field:catname /]</h4>
                            <h4>功能：[field:gongneng /]</h4>
                        </div>
                    </div>
                </a>
            </li>