<li class="img_nav">
                <a href="[field:arcurl /]"  class="nav_a clearfix">
                    <img src="[field:litpic /]"  onerror="no_pic(this);" />
                    <div class="case_bg">
                        <div class="case-box">
                            <h4>功能：[field:gongneng /]</h4>
                        </div>
                    </div>
                </a>
            </li>