<?php
$z[0]=Array("array","\r\n                if (@me['platform'] == '微信公众号') {\r\n                    echo 123;\r\n                }\r\n            ",0,165);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",226,242);
$z[1][4]=array();
$z[2]=Array("litpic","",299,315);
$z[2][4]=array();
$z[3]=Array("title","",502,517);
$z[3][4]=array();
$z[4]=Array("catname","",565,582);
$z[4][4]=array();
$z[5]=Array("gongneng","",634,652);
$z[5][4]=array();

?>