<?php
$z[0]=Array("array","\r\n                if (@me['platform'] == '微信公众号') {\r\n                  @me='123';\r\n                }\r\n            ",0,164);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",225,241);
$z[1][4]=array();
$z[2]=Array("litpic","",298,314);
$z[2][4]=array();
$z[3]=Array("title","",501,516);
$z[3][4]=array();
$z[4]=Array("catname","",564,581);
$z[4][4]=array();
$z[5]=Array("gongneng","",633,651);
$z[5][4]=array();

?>