<li class="deputy_li">
                <a href="[field:arcurl /]"  class="deputy_a clearfix">
                    <img src="[field:litpic /]" onerror="no_pic(this);" />
                    <div class="deputy_bg">
                        <h4>[field:title /]</h4>
                        <span></span>
                        <p>[field:gongneng /]</p>
                    </div>
                </a>
            </li>