<li class="deputy_li">
                <a href="[field:arcurl /]" class="deputy_a clearfix">
                    <img src="[field:litpic /]" onerror="no_pic(this);" />
                    <div class="deputy_bg">
                        <h4>名称：[field:title /]</h4>
                        <span></span>
                        <p>类型：[field:catname /]</p>
                    </div>
                </a>
            </li>