<?php
$z[0]=Array("global","",237,261);
$z[0][4]=array();
$z[0][4]['name']="cfg_cdtel";
$z[1]=Array("global","",283,307);
$z[1][4]=array();
$z[1][4]['name']="cfg_cdtel";
$z[2]=Array("sql","\r\n          <div class=\"banner_list ai-banner-[field:id /]\" style=\"background: url([field:url /]) no-repeat center center;background-size:cover;\" >                \r\n          </div>  \r\n          ",1360,1635);
$z[2][4]=array();
$z[2][4]['sql']="SELECT * FROM dede_banner order by sort desc limit 5";

?>