<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:58:52
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:58:52
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:58:56
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:58:56
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:58:59
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:58:59
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM xly_category   WHERE (catname LIKE '%%') LIMIT 0,1;</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /admin/cat_list.php
Error: Table 'dintercms.xly_category' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM xly_category   WHERE (catname LIKE '%%')  ORDER BY sort DESC LIMIT 0,20</font>
Time2018-02-08 09:59:00
*/
?>
<?php  exit();
/*
Page: /
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE dc.cattype='\xE5\xBE\xAE\xE4\xBF\xA1\xE5\x85\xAC\xE4\xBC\x97\xE5\x8F\xB7' ' at line 1 <br />Error sql: <font color='red'>SELECT dc.*,d.catname FROM dede_cases as dc left join dede_category as d WHERE dc.cattype='微信公众号' and dc.catid=d.id order by dc.sort desc limit 9</font>
Time2018-02-08 11:11:52
*/
?>
<?php  exit();
/*
Page: /plus/cases.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=5 order by uptime desc limit 1</font>
Time2018-02-08 11:28:19
*/
?>
<?php  exit();
/*
Page: /plus/cases.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=5 order by uptime desc limit 1</font>
Time2018-02-08 11:44:51
*/
?>
<?php  exit();
/*
Page: /plus/small.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=2 order by uptime desc limit 1</font>
Time2018-02-08 11:45:24
*/
?>
<?php  exit();
/*
Page: /plus/small.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=2 order by uptime desc limit 1</font>
Time2018-02-08 11:49:50
*/
?>
<?php  exit();
/*
Page: /plus/small.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=2 order by uptime desc limit 1</font>
Time2018-02-08 11:49:59
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:06
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:06
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:20
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:21
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:21
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=3 order by uptime desc limit 1</font>
Time2018-02-08 11:54:40
*/
?>
<?php  exit();
/*
Page: /plus/dev_wx.php
Error: Unknown column 'opentype' in 'field list' <br />Error sql: <font color='red'>SELECT id,title,url,brief,opentype FROM dede_cases where opentype like '%微信%' order by sort desc limit 4</font>
Time2018-02-08 11:54:40
*/
?>
<?php  exit();
/*
Page: /plus/devapp.php
Error: Unknown column 'position' in 'where clause' <br />Error sql: <font color='red'>SELECT * FROM dede_uploads where position=4 order by uptime desc limit 1</font>
Time2018-02-08 11:56:26
*/
?>
